import { React, useState } from 'react'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Nav from './components/Nav'
import Stake from './components/Stake'
import About from './components/About'
import Home from './components/Home'
import SignIn from './components/SignIn'


export default function App() {
  const [page, setPage] = useState('Home')

  return (
    <div className={styles.container}>
      <Head>
        <title>EcoCitizen</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.navBar}>
        <div>
          <button onClick={() => setPage('Stake')}>Stake</button>
          <button onClick={() => setPage('About')}>About</button>
          <button onClick={() => setPage('Home')}>Home</button>
        </div>
        <div>
          <SignIn />
        </div>
      </div>
      {(page == 'Home') ? <Home /> : (page == 'Stake') ? <Stake /> : <About />}

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
        <a
          href='https://www.svgbackgrounds.com/'
          target="_blank"
          rel='noopener noreferrer'
        ><h4>Background supplied by SVGBackGrounds</h4></a>
      </footer>
    </div>
  )
}
